service: <fill-in-name>

stage: prod
region: us-east-1

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-dynamic-dotenv
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-webpack

functions:
  hello:
    handler: src/handler.hello

    events:
      - http:
          path: hello
          method: get

