service: <fill-in-name>

stage: prod
region: us-east-1

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamic-dotenv

package:
  include:
    handler.ts

functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: hello
          method: post

